#!/usr/bin/env bash
# Bash script that will display information about the subdomains

dns_config () {
    # Function to retrieve DNS information for a given domain and subdomain
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    # Format and print the result
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

# Check if only the domain is provided
if [ "$#" == 1 ]
then
  # Display information for all specified subdomains
  dns_config "$1" "www"
  dns_config "$1" "lb-01"
  dns_config "$1" "web-01"
  dns_config "$1" "web-02"
elif [ "$#" == 2 ]
then
  # Display information for the specific subdomain
  dns_config "$1" "$2"
fi
