#!/usr/bin/env bash
#fizzbuzz

i=1
while ((i<=100)); do

    if ((!(i%3) && !(i%5))); then
        echo "FizzBuzz"
    elif (( i%5 && !(i%3) )); then
        echo "Fizz"
    elif (( i%3 && !(i%5) )); then
        echo "Buzz"
    else
        echo "$i"
    fi
    ((i++))
done